### ISSUE TITLE
Looks like a 500

### ISSUE THREAD

**Issue by drewish** [tyhyten/OrbWeaver#1]
Clever idea for a project. I was looking at it last week and it was working but tried to pull it up again today and it seems to be giving a 500:

![screenshot 2015-05-26 13 00 45](https://cloud.githubusercontent.com/assets/68750/7821986/56e1848e-03a7-11e5-8b13-c6d5bdcda377.png)

**Comment by tyhyten** [comment]
Hi Andrew,

Thanks for pointing that out! I wasn't aware. I checked the logs and was
getting a 429 (too many requests) back from Spotify. I guess that's a good
thing. I didn't have it set to authenticate the app until the user
authenticated, so I probably had a super low rate limit. It should be
working again whenever that resets.

Ty Hyten
tyhyten.com
618.910.4999
